program FaturamentoDiario;


uses
  Forms,
  Dialogs,
  APrincipal in 'APrincipal.pas' {FPrincipal},
  Abertura in '..\MaGerais\Abertura.pas' {FAbertura},
  Constantes in '..\MConfiguracoesSistema\Constantes.pas',
  UnAtualizacao in '..\MaGerais\UnAtualizacao.pas',
  AMenssagemAtualizando in 'AMenssagemAtualizando.pas' {FMensagemAtualizando},
  UnSistema in '..\magerais\UnSistema.pas',
  AFaturamentoDiario in '..\mpontaloja\AFaturamentoDiario.pas' {FFaturamentoDiario},
  UnDadosProduto in '..\mestoque\UnDadosProduto.pas',
  UnDados in '..\magerais\UnDados.pas',
  UnCotacao in '..\mpontaloja\UnCotacao.pas',
  UnContasAPagar in '..\mfinanceiro\UnContasAPagar.pas',
  UnContasAReceber in '..\mfinanceiro\UnContasAReceber.pas',
  UnComissoes in '..\mfinanceiro\UnComissoes.pas',
  unmoedas in '..\mconfiguracoessistema\unmoedas.pas',
  UnDadosCR in '..\mfinanceiro\UnDadosCR.pas',
  UnClassesImprimir in '..\magerais\UnClassesImprimir.pas',
  AMostraParReceberOO in '..\mfinanceiro\AMostraParReceberOO.pas' {FMostraParReceberOO},
  AContas in '..\mfinanceiro\AContas.pas' {FContas},
  abancos in '..\mfinanceiro\abancos.pas' {FBancos},
  UnProdutos in '..\mestoque\UnProdutos.pas',
  uncodigobarra in '..\mconfiguracoessistema\uncodigobarra.pas',
  unclassificacao in '..\mestoque\unclassificacao.pas',
  UnSumarizaEstoque in '..\mestoque\UnSumarizaEstoque.pas',
  amostracheque in '..\magerais\amostracheque.pas' {FMostraCheque},
  UnImpressao in '..\magerais\UnImpressao.pas',
  UnClientes in '..\magerais\UnClientes.pas',
  UnNotaFiscal in '..\mfaturamento\UnNotaFiscal.pas',
  UnComandosImpCheque in '..\magerais\UnComandosImpCheque.pas',
  ANovoECF in '..\mpontaloja\ANovoECF.pas' {FNovoECF},
  UnECF in '..\mpontaloja\UnECF.pas',
  ALocalizaProdutos in '..\mfaturamento\ALocalizaProdutos.pas' {FlocalizaProduto},
  AProdutosKit in '..\mestoque\AProdutosKit.pas' {FProdutosKit},
  AProdutos in '..\mestoque\AProdutos.pas' {Fprodutos},
  ANovaClassificacao in '..\mestoque\ANovaClassificacao.pas' {FNovaClassificacao},
  AMontaKit in '..\mestoque\AMontaKit.pas' {FMontaKit},
  alocalizaclassificacao in '..\mestoque\alocalizaclassificacao.pas' {FLocalizaClassificacao},
  ACores in '..\mestoque\ACores.pas' {FCores},
  ATipoFundo in '..\mestoque\ATipoFundo.pas' {FTipoFundo},
  ATipoEmenda in '..\mestoque\ATipoEmenda.pas' {FTipoEmenda},
  AMaquinas in '..\mestoque\AMaquinas.pas' {FMaquinas},
  AEstagioProducao in '..\mestoque\AEstagioProducao.pas' {FEstagioProducao},
  ATipoEstagioProducao in '..\mestoque\ATipoEstagioProducao.pas' {FTipoEstagioProducao},
  ATipoCorte in '..\mestoque\ATipoCorte.pas' {FTipoCorte},
  ANovoCliente in '..\magerais\ANovoCliente.pas' {FNovoCliente},
  AClientes in '..\magerais\AClientes.pas' {FClientes},
  ACotacao in '..\mpontaloja\ACotacao.pas' {FCotacao},
  UnCrystal in '..\magerais\UnCrystal.pas',
  ANovaCotacao in '..\mpontaloja\ANovaCotacao.pas' {FNovaCotacao},
  ANovoVendedor in '..\magerais\ANovoVendedor.pas' {FNovoVendedor},
  AVendedores in '..\magerais\AVendedores.pas' {FVendedores},
  AConsultaRuas in '..\magerais\AConsultaRuas.pas' {FConsultaRuas},
  ACadCidades in '..\magerais\ACadCidades.pas' {FCidades},
  ACadPaises in '..\magerais\ACadPaises.pas' {FCadPaises},
  ACadEstados in '..\magerais\ACadEstados.pas' {FCadEstados},
  acadlogradouro in '..\magerais\acadlogradouro.pas' {FCadLogradouros},
  AConsultaCondicaoPgto in '..\magerais\AConsultaCondicaoPgto.pas' {FConsultaCondicaoPgto},
  AFormasPagamento in '..\mfinanceiro\AFormasPagamento.pas' {FFormasPagamento},
  anovoservico in '..\mestoque\anovoservico.pas' {FNovoServico},
  unservicos in '..\mestoque\unservicos.pas',
  aservicos in '..\mestoque\aservicos.pas' {FServicos},
  alocalizaservico in '..\mfaturamento\alocalizaservico.pas' {FlocalizaServico},
  AImpCotacao in '..\mpontaloja\AImpCotacao.pas' {FImpOrcamento},
  UnVendedor in '..\magerais\UnVendedor.pas',
  ANovaTransportadora in '..\magerais\ANovaTransportadora.pas' {FNovaTransportadora},
  atransportadoras in '..\magerais\atransportadoras.pas' {FTransportadoras},
  ATipoCotacao in '..\mpontaloja\ATipoCotacao.pas' {FTipoCotacao},
  aoperacoesestoques in '..\mestoque\aoperacoesestoques.pas' {FOperacoesEstoques},
  APlanoConta in '..\mfinanceiro\APlanoConta.pas' {FPlanoConta},
  ANovoPlanoConta in '..\mfinanceiro\ANovoPlanoConta.pas' {FNovoPlanoConta},
  AEmbalagem in '..\mpontaloja\AEmbalagem.pas' {FEmbalagem},
  AProdutoReferencia in '..\mpontaloja\AProdutoReferencia.pas' {FReferenciaProduto},
  AProdutosDevolvidos in '..\mpontaloja\AProdutosDevolvidos.pas' {FProdutosDevolvidos},
  AMostraObservacaoCliente in '..\mpontaloja\AMostraObservacaoCliente.pas' {FMostraObservacaoCliente},
  ANovaNotaFiscaisFor in '..\mestoque\ANovaNotaFiscaisFor.pas' {FNovaNotaFiscaisFor},
  UnNotasFiscaisFor in '..\mestoque\UnNotasFiscaisFor.pas',
  AItensNatureza in '..\mfaturamento\AItensNatureza.pas' {FItensNatureza},
  ANovaNatureza in '..\mfaturamento\ANovaNatureza.pas' {FNovaNatureza},
  ANaturezas in '..\mfaturamento\ANaturezas.pas' {FNaturezas},
  amovnatureza in '..\mfaturamento\amovnatureza.pas' {FMovNatureza},
  ANovoTecnico in '..\mpontaloja\ANovoTecnico.pas' {FNovoTecnico},
  ATecnicos in '..\mpontaloja\ATecnicos.pas' {FTecnicos},
  ANovaNotaFiscalNota in '..\mfaturamento\ANovaNotaFiscalNota.pas' {FNovaNotaFiscalNota},
  UnOrdemProducao in '..\mestoque\UnOrdemProducao.pas',
  aobservacoesnota in '..\mfaturamento\aobservacoesnota.pas' {FObservacoesNota},
  AImprimeEtiqueta in '..\mpontaloja\AImprimeEtiqueta.pas' {FImprimiEtiqueta},
  UnImpressaoEtiquetaCotacao in '..\mpontaloja\UnImpressaoEtiquetaCotacao.pas',
  AGeraOP in '..\mpontaloja\AGeraOP.pas' {FGerarOP},
  ANovaOrdemProducaoCadarco in '..\mestoque\ANovaOrdemProducaoCadarco.pas' {FNovaOrdemProducaoCadarco},
  AGeraEstagiosOP in '..\mpontaloja\AGeraEstagiosOP.pas' {FGeraEstagiosOP},
  ABaixaParcialCotacao in '..\mpontaloja\ABaixaParcialCotacao.pas' {FBaixaParcialCotacao},
  AConsultaBaixaParcial in '..\mpontaloja\AConsultaBaixaParcial.pas' {FConsultaBaixaParcial},
  AOrdensProducaoCadarco in '..\mestoque\AOrdensProducaoCadarco.pas' {FOrdensProducaoCadarco},
  ANovaCobranca in '..\mfinanceiro\ANovaCobranca.pas' {FNovaCobranca},
  AHistoricoLigacao in '..\mfinanceiro\AHistoricoLigacao.pas' {FHistoricoLigacao},
  ACobrancas in '..\mfinanceiro\ACobrancas.pas' {FCobrancas},
  aprofissoes in '..\magerais\aprofissoes.pas' {FProfissoes},
  asituacoesclientes in '..\magerais\asituacoesclientes.pas' {FSituacoesClientes},
  aregiaovenda in '..\magerais\aregiaovenda.pas' {FRegiaoVenda},
  ARamoAtividade in '..\mpontaloja\ARamoAtividade.pas' {FRamoAtividade},
  AFormaPagamentoECF in '..\mpontaloja\AFormaPagamentoECF.pas' {FFormaPagamentoECF},
  UnImpressaoBoleto in '..\magerais\UnImpressaoBoleto.pas',
  AMotivoInadimplencia in '..\mfinanceiro\AMotivoInadimplencia.pas' {FMotivoInadimplencia},
  ANovoContratoCliente in '..\mpontaloja\ANovoContratoCliente.pas' {FNovoContratoCliente},
  UnContrato in '..\mpontaloja\UnContrato.pas',
  ATipoContrato in '..\mpontaloja\ATipoContrato.pas' {FTipoContrato},
  ANovaConta in '..\mfinanceiro\ANovaConta.pas' {FNovaConta},
  AContratosCliente in '..\mpontaloja\AContratosCliente.pas' {FContratosCliente},
  ANovoTeleMarketing in '..\mpontaloja\ANovoTeleMarketing.pas' {FNovoTeleMarketing},
  UnTeleMarketing in '..\mpontaloja\UnTeleMarketing.pas',
  AAlteraVendedorCotacao in '..\mpontaloja\AAlteraVendedorCotacao.pas' {FAlteraVendedorCotacao},
  ABrindesCliente in '..\mpontaloja\ABrindesCliente.pas' {FBrindesCliente},
  ATeleMarketings in '..\mpontaloja\ATeleMarketings.pas' {FTeleMarketings},
  AProdutosCliente in '..\mpontaloja\AProdutosCliente.pas' {FProdutosCliente},
  UnDaruma in '..\mpontaloja\UnDaruma.pas',
  ADonoProduto in '..\mpontaloja\ADonoProduto.pas' {FDonoProduto},
  ANovoAgendamento in '..\mpontaloja\ANovoAgendamento.pas' {FNovoAgedamento},
  ATipoAgendamento in '..\mpontaloja\ATipoAgendamento.pas' {FTipoAgendamento},
  AAcondicionamento in '..\mpontaloja\AAcondicionamento.pas' {FAcondicionamento},
  AGeraFracaoOP in '..\mpontaloja\AGeraFracaoOP.pas' {FGeraFracaoOP},
  AParentesCliente in '..\mpontaloja\AParentesCliente.pas' {FParentesClientes},
  ANovoChamadoTecnico in '..\MChamado\ANovoChamadoTecnico.pas' {FNovoChamado},
  UnChamado in '..\MChamado\UnChamado.pas',
  ANovaOrdemProducaoGenerica in '..\mestoque\ANovaOrdemProducaoGenerica.pas' {FNovaOrdemProducaoGenerica},
  AOrdemProducaoGenerica in '..\mestoque\AOrdemProducaoGenerica.pas' {FOrdemProducaoGenerica},
  AAlteraEstagioCotacao in '..\mpontaloja\AAlteraEstagioCotacao.pas' {FAlteraEstagioCotacao},
  AAlteraEstagioChamado in '..\mpontaloja\AAlteraEstagioChamado.pas' {FAlteraEstagioChamado},
  AHistoricoECobranca in '..\mfinanceiro\AHistoricoECobranca.pas' {FHistoricoECobranca},
  ALocalizaProdutoContrato in '..\MChamado\ALocalizaProdutoContrato.pas' {FLocalizaProdutoContrato},
  AAgendaChamados in '..\MChamado\AAgendaChamados.pas' {FAgendaChamados},
  AChamadosTecnicos in '..\MChamado\AChamadosTecnicos.pas' {FChamadoTecnico},
  AHoraAgendaChamado in '..\MChamado\AHoraAgendaChamado.pas' {FHoraAgendaChamado},
  AEfetuarPesquisaSatisfacao in '..\MChamado\AEfetuarPesquisaSatisfacao.pas' {FEfetuarPesquisaSatisfacao},
  UnPesquisaSatisfacao in '..\MChamado\UnPesquisaSatisfacao.pas',
  AMedico in '..\mpontaloja\AMedico.pas' {FMedico},
  ANovaMaquina in '..\mestoque\ANovaMaquina.pas' {FNovaMaquina},
  UnArgox in '..\magerais\UnArgox.pas',
  ATamanhos in '..\mpontaloja\ATamanhos.pas' {FTamanhos},
  APedidosPendentesFaturar in '..\mpontaloja\APedidosPendentesFaturar.pas' {FPedidosPendentesFaturar},
  UnProspect in '..\mcrm\UnProspect.pas',
  AContatosCliente in '..\mpontaloja\AContatosCliente.pas' {FContatosCliente},
  AProdutosReserva in '..\mpontaloja\AProdutosReserva.pas' {FProdutosReserva},
  AChequesCP in '..\mfinanceiro\AChequesCP.pas' {FChequesCP},
  AConsultacheques in '..\mfinanceiro\AConsultacheques.pas' {FConsultaCheques},
  UnVersoes in '..\magerais\UnVersoes.pas',
  UnAmostra in '..\mcrm\UnAmostra.pas',
  UnCaixa in '..\mcaixa\UnCaixa.pas',
  AMostraParPagarOO in '..\mfinanceiro\AMostraParPagarOO.pas' {FMostraParPagarOO},
  UnZebra in '..\magerais\UnZebra.pas',
  ANovoProdutoPro in '..\mestoque\ANovoProdutoPro.pas' {FNovoProdutoPro},
  AMontaKitBastidor in '..\mestoque\AMontaKitBastidor.pas' {FMontaKitBastidor},
  AGerarFracaoOPMaquinasCorte in '..\mpontaloja\AGerarFracaoOPMaquinasCorte.pas' {FGerarFracaoOPMaquinasCorte},
  UnSolicitacaoCompra in '..\mestoque\UnSolicitacaoCompra.pas',
  APedidosCompraAberto in '..\mestoque\APedidosCompraAberto.pas' {FPedidosCompraAberto},
  UnPedidoCompra in '..\mestoque\UnPedidoCompra.pas',
  ANovoPedidoCompra in '..\mestoque\ANovoPedidoCompra.pas' {FNovoPedidoCompra},
  ABaixaConsumoProduto in '..\mestoque\ABaixaConsumoProduto.pas' {FBaixaConsumoProduto},
  ANovaSolicitacaoCompra in '..\mestoque\ANovaSolicitacaoCompra.pas' {FNovaSolicitacaoCompras},
  ACompradores in '..\mestoque\ACompradores.pas' {FCompradores},
  ASolicitacaoCompras in '..\mestoque\ASolicitacaoCompras.pas' {FSolicitacaoCompra},
  AAlteraEstagioOrcamento in '..\mestoque\AAlteraEstagioOrcamento.pas' {FAlteraEstagioOrcamentoCompra},
  ASolicitacaoCompraProdutosPendentes in '..\mestoque\ASolicitacaoCompraProdutosPendentes.pas' {FSolicitacaoCompraProdutosPendentes},
  APedidoCompra in '..\mestoque\APedidoCompra.pas' {FPedidoCompra},
  AAlteraEstagioPedidoCompra in '..\mestoque\AAlteraEstagioPedidoCompra.pas' {FAlteraEstagioPedidoCompra},
  APropostasCliente in '..\mcrm\APropostasCliente.pas' {FPropostasCliente},
  UnProposta in '..\mcrm\UnProposta.pas',
  ANovaProposta in '..\mcrm\ANovaProposta.pas' {FNovaProposta},
  ANovoProspect in '..\mcrm\ANovoProspect.pas' {FNovoProspect},
  AProspects in '..\mcrm\AProspects.pas' {FProspects},
  ANovaAgendaProspect in '..\mcrm\ANovaAgendaProspect.pas' {FNovaAgendaProspect},
  ANovoTelemarketingProspect in '..\mcrm\ANovoTelemarketingProspect.pas' {FNovoTelemarketingProspect},
  AProdutosProspect in '..\mcrm\AProdutosProspect.pas' {FProdutosProspect},
  AContatosProspect in '..\mcrm\AContatosProspect.pas' {FContatosProspect},
  AAlteraEstagioProposta in '..\mcrm\AAlteraEstagioProposta.pas' {FAlteraEstagioProposta},
  ANovoLembrete in '..\mpontaloja\ANovoLembrete.pas' {FNovoLembrete},
  UnLembrete in '..\mpontaloja\UnLembrete.pas',
  ASelecionarUsuarios in '..\mpontaloja\ASelecionarUsuarios.pas' {FSelecionarUsuarios},
  AVerificaLeituraLembrete in '..\MChamado\AVerificaLeituraLembrete.pas' {FVerificaLeituraLembrete},
  AProdutosOrcados in '..\MChamado\AProdutosOrcados.pas' {FProdutosOrcados},
  ATipoChamado in '..\MChamado\ATipoChamado.pas' {FTipoChamado},
  AMeioDivulgacao in '..\mcrm\AMeioDivulgacao.pas' {FMeioDivulgacao},
  AConcorrentes in '..\mcrm\AConcorrentes.pas' {FConcorrentes},
  ANovoConcorrente in '..\mcrm\ANovoConcorrente.pas' {FNovoConcorrente},
  AMotivoVenda in '..\mcrm\AMotivoVenda.pas' {FMotivoVenda},
  ASetores in '..\mcrm\ASetores.pas' {FSetores},
  ANovoSetor in '..\mcrm\ANovoSetor.pas' {FNovoSetor},
  ATipoProposta in '..\mcrm\ATipoProposta.pas' {FTipoProposta},
  ABaixaProdutosChamado in '..\MChamado\ABaixaProdutosChamado.pas' {FBaixaProdutosChamado},
  AConsultaChamadoParcial in '..\MChamado\AConsultaChamadoParcial.pas' {FConsultaChamadoParcial},
  ARelOrdemSerra in '..\mestoque\ARelOrdemSerra.pas' {FRelOrdemSerra},
  AAlteraEstagioFracaoOP in '..\mestoque\AAlteraEstagioFracaoOP.pas' {FAlteraEstagioFracaoOP},
  AContasAReceber in '..\mfinanceiro\AContasAReceber.pas' {FContasaReceber},
  ANovoContasaReceber in '..\mfinanceiro\ANovoContasaReceber.pas' {FNovoContasAReceber},
  agraficoscontasareceber in '..\mfinanceiro\agraficoscontasareceber.pas' {FGraficosCR},
  AManutencaoCR in '..\mfinanceiro\AManutencaoCR.pas' {FManutencaoCR},
  ABaixaContasAReceberOO in '..\mfinanceiro\ABaixaContasAReceberOO.pas' {FBaixaContasaReceberOO},
  AChequesOO in '..\mfinanceiro\AChequesOO.pas' {FChequesOO},
  AMovComissoes in '..\mfinanceiro\AMovComissoes.pas' {FMovComissoes},
  AConsolidarCR in '..\mfinanceiro\AConsolidarCR.pas' {FConsolidarCR},
  AContasAConsolidarCR in '..\mfinanceiro\AContasAConsolidarCR.pas' {FContasAConsolidarCR},
  AVisualizaLogReceber in '..\mfinanceiro\AVisualizaLogReceber.pas' {FVisualizaLogReceber},
  AContasAPagar in '..\mfinanceiro\AContasAPagar.pas' {FContasaPagar},
  undespesas in '..\mfinanceiro\undespesas.pas',
  ANovoContasaPagar in '..\mfinanceiro\ANovoContasaPagar.pas' {FNovoContasAPagar},
  adespesas in '..\mfinanceiro\adespesas.pas' {FDespesas},
  ACentroCusto in '..\mfinanceiro\ACentroCusto.pas' {FCentroCusto},
  ageradespesasfixas in '..\mfinanceiro\ageradespesasfixas.pas' {FGeraDespesasFixas},
  AImprimeCP in '..\mfinanceiro\AImprimeCP.pas' {FImprimeCP},
  AGraficosContasaPagar in '..\mfinanceiro\AGraficosContasaPagar.pas' {FGraficosCP},
  AManutencaoCP in '..\mfinanceiro\AManutencaoCP.pas' {FManutencaoCP},
  ABaixaContasaPagarOO in '..\mfinanceiro\ABaixaContasaPagarOO.pas' {FBaixaContasaPagarOO},
  ACompensaCheque in '..\mfinanceiro\ACompensaCheque.pas' {FCompensaCheque},
  ANovoEmailContasAReceber in '..\mfinanceiro\ANovoEmailContasAReceber.pas' {FNovoEmailContasAReceber},
  ACreditoCliente in '..\mfinanceiro\ACreditoCliente.pas' {FCreditoCliente},
  AComissaoClassificacaoVendedor in '..\mestoque\AComissaoClassificacaoVendedor.pas' {FComissaoClassificacaoVendedor},
  unEMarketing in '..\mpontaloja\unEMarketing.pas',
  ANovoOrcamentoCompra in '..\mestoque\ANovoOrcamentoCompra.pas' {FNovoOrcamentoCompra},
  UnOrcamentoCompra in '..\mestoque\UnOrcamentoCompra.pas',
  AHorarioTrabalho in '..\mestoque\AHorarioTrabalho.pas' {FHorarioTrabalho},
  AFaixaEtaria in '..\mpontaloja\AFaixaEtaria.pas' {FFaixaEtaria},
  AMarcas in '..\mpontaloja\AMarcas.pas' {FMarca},
  AAlteraEstagioAgendamento in '..\mpontaloja\AAlteraEstagioAgendamento.pas' {FAlteraEstagioAgendamento},
  AAgendamentos in '..\mpontaloja\AAgendamentos.pas' {FAgendamentos},
  AMetasVendedor in '..\mpontaloja\AMetasVendedor.pas' {FMetasVendedor},
  AConsultaLogSeparacaoConsumo in '..\mestoque\AConsultaLogSeparacaoConsumo.pas' {FConsultaLogSeparacaoConsumo},
  UnRave in '..\magerais\UnRave.pas',
  dmRave in '..\magerais\dmRave.pas' {dtRave: TDSServerModule},
  AComposicoes in '..\mestoque\AComposicoes.pas' {FComposicoes},
  ANovaComposicao in '..\mestoque\ANovaComposicao.pas' {FNovaComposicao},
  UnNFe in '..\mfaturamento\UnNFe.pas',
  ACondicaoPagamento in '..\mpontaloja\ACondicaoPagamento.pas' {FCondicaoPagamento},
  ANovaCondicaoPagamento in '..\mpontaloja\ANovaCondicaoPagamento.pas' {FNovaCondicaoPagamento},
  UnCondicaoPagamento in '..\mfinanceiro\UnCondicaoPagamento.pas',
  AGeraFracaoOPProdutos in '..\mestoque\AGeraFracaoOPProdutos.pas' {FGeraFracaoOPProdutos},
  AProjetos in '..\mfinanceiro\AProjetos.pas' {FProjetos},
  UnDRave in '..\magerais\UnDRave.pas',
  UnProgramador1 in '..\magerais\UnProgramador1.pas',
  ACorpoEmailProposta in '..\mcrm\ACorpoEmailProposta.pas' {FCorpoEmailProposta},
  AMostraEstoqueChapas in '..\mestoque\AMostraEstoqueChapas.pas' {FMostraEstoqueChapas},
  AAcessorio in '..\mestoque\AAcessorio.pas' {FAcessorio},
  AAplicacao in '..\mcrm\AAplicacao.pas' {FAplicacao},
  AAdicionaProdutosTerceirizacao in '..\mestoque\AAdicionaProdutosTerceirizacao.pas' {FAdicionaProdutosTerceirizacao},
  ALocalizaFracaoOP in '..\mestoque\ALocalizaFracaoOP.pas' {FLocalizaFracaoOP},
  ANovoEstagio in '..\mestoque\ANovoEstagio.pas' {FNovoEstagio},
  AComandoFiscalFiltro in '..\mefiPDV\AComandoFiscalFiltro.pas' {FComandoFiscalFiltro},
  AMenuFiscalECF in '..\mefiPDV\AMenuFiscalECF.pas' {FMenuFiscalECF},
  UnSpedFiscal in '..\mfaturamento\UnSpedFiscal.pas',
  AOPProdutosAReservar in '..\mestoque\AOPProdutosAReservar.pas' {FOPProdutosAReservar},
  AOrcamentoCompras in '..\mestoque\AOrcamentoCompras.pas' {FOrcamentoCompras},
  AMapaCompras in '..\mestoque\AMapaCompras.pas' {FMapaCompras},
  ASelecionarFornecedorMapaCompras in '..\mestoque\ASelecionarFornecedorMapaCompras.pas' {FSelecionaFornecedorMapaCompras};

{$R *.RES}

begin
  Application.Initialize;


  Application.CreateForm(TFPrincipal, FPrincipal);
  FPrincipal.VplParametroBaseDados := 'SisCorp';
  varia.ParametroBase := 'Siscorp';
  FPrincipal.Showmodal;
end.
