program configuracoessistema;


uses
  Forms,
  SysUtils,
  RpDefine,
  FunString,
  APrincipal in 'APrincipal.pas' {FPrincipal},
  ANovoUsuario in 'ANovoUsuario.pas' {FNovoUsuario},
  AUsuarios in 'AUsuarios.pas' {FUsuarios},
  Constantes in 'Constantes.pas',
  AFiliais in 'AFiliais.pas' {FFiliais},
  ANovaFilial in 'ANovaFilial.pas' {FNovaFilial},
  AEmpresas in 'AEmpresas.pas' {FEmpresas},
  AGrupos in 'AGrupos.pas' {FGrupos},
  CadFormularios in 'CadFormularios.pas' {FCadFormularios},
  AMoedas in 'AMoedas.pas' {FMoedas},
  AMoedaDia in 'AMoedaDia.pas' {FMoedaDia},
  AMovMoeda in 'AMovMoeda.pas' {FMovMoedas},
  AConfiguracaoGeral in 'AConfiguracaoGeral.pas' {FConfiguracoesGeral},
  Abertura in '..\MaGerais\Abertura.pas' {FAbertura},
  ASobre in '..\MaGerais\ASobre.pas' {FSobre},
  AConfiguracaoProdutos in 'AConfiguracaoProdutos.pas' {FConfiguracoesProdutos},
  AConfiguracaoFinanceiro in 'AConfiguracaoFinanceiro.pas' {FConfiguracoesFinanceiro},
  AConfiguracaoFiscal in 'AConfiguracaoFiscal.pas' {FConfiguracoesFiscal},
  ARegistroSistema in 'ARegistroSistema.pas' {FRegistroSistema},
  UnRegistro in '..\MConfiguraModulos\UnRegistro.pas',
  AImportaEnder in 'AImportaEnder.pas' {FImportaEnderecos},
  AConsultaRuas in '..\MaGerais\AConsultaRuas.pas' {FConsultaRuas},
  ACadCidades in '..\MaGerais\ACadCidades.pas' {FCidades},
  ACadEstados in '..\MaGerais\ACadEstados.pas' {FCadEstados},
  ACadPaises in '..\MaGerais\ACadPaises.pas' {FCadPaises},
  UnCodigoBarra in 'UnCodigoBarra.pas',
  AConfiguracaoImpressao in 'AConfiguracaoImpressao.pas' {FConfiguraImpressao},
  UnImpressao in '..\MaGerais\UnImpressao.pas',
  AAlterarSenha in '..\MaGerais\AAlterarSenha.pas' {FAlteraSenha},
  AAlterarFilialUso in '..\MaGerais\AAlterarFilialUso.pas' {FAlterarFilialUso},
  AConfigImpNotaFiscal in 'AConfigImpNotaFiscal.pas' {FConfigImpNotaFiscal},
  UnClassesImprimir in '..\MaGerais\UnClassesImprimir.pas',
  APlanoConta in '..\MFinanceiro\APlanoConta.pas' {FPlanoConta},
  ANovoPlanoConta in '..\MFinanceiro\ANovoPlanoConta.pas' {FNovoPlanoConta},
  ATextoBoletos in 'ATextoBoletos.pas' {FTextoBoletos},
  ADriveImpressora in 'ADriveImpressora.pas' {FDriveImpressora},
  AComandosImpressora in 'AComandosImpressora.pas' {FComandosImpressora},
  UnAtualizacao in '..\MaGerais\UnAtualizacao.pas',
  UnPrincipal in '..\MaGerais\UnPrincipal.pas',
  AItensNatureza in '..\MFaturamento\AItensNatureza.pas' {FItensNatureza},
  ANovoGrupo in 'ANovoGrupo.pas' {FNovoGrupo},
  UnDados in '..\magerais\UnDados.pas',
  UnDadosProduto in '..\mestoque\UnDadosProduto.pas',
  UnClientes in '..\magerais\UnClientes.pas',
  UnNotaFiscal in '..\mfaturamento\UnNotaFiscal.pas',
  UnCotacao in '..\mpontaloja\UnCotacao.pas',
  UnContasAReceber in '..\mfinanceiro\UnContasAReceber.pas',
  UnComissoes in '..\mfinanceiro\UnComissoes.pas',
  UnDadosCR in '..\mfinanceiro\UnDadosCR.pas',
  AMostraParReceberOO in '..\mfinanceiro\AMostraParReceberOO.pas' {FMostraParReceberOO},
  acontas in '..\mfinanceiro\acontas.pas' {FContas},
  abancos in '..\mfinanceiro\abancos.pas' {FBancos},
  UnProdutos in '..\mestoque\UnProdutos.pas',
  unclassificacao in '..\mestoque\unclassificacao.pas',
  UnSumarizaEstoque in '..\mestoque\UnSumarizaEstoque.pas',
  UnContasAPagar in '..\mfinanceiro\UnContasAPagar.pas',
  uncomandosimpcheque in '..\magerais\uncomandosimpcheque.pas',
  AConfiguracaoEmpresa in 'AConfiguracaoEmpresa.pas' {FConfiguracaoEmpresa},
  UnSistema in '..\magerais\UnSistema.pas',
  AConfiguracaoFilial in 'AConfiguracaoFilial.pas' {FConfiguracaoFilial},
  AConfiguracaoECF in 'AConfiguracaoECF.pas' {FConfiguracaoECF},
  UnECF in '..\mpontaloja\UnECF.pas',
  ANovaConta in '..\mfinanceiro\ANovaConta.pas' {FNovaConta},
  ANovoCliente in '..\magerais\ANovoCliente.pas' {FNovoCliente},
  AClientes in '..\magerais\AClientes.pas' {FClientes},
  ACotacao in '..\mpontaloja\ACotacao.pas' {FCotacao},
  UnImpressaoBoleto in '..\magerais\UnImpressaoBoleto.pas',
  ALocalizaProdutos in '..\mfaturamento\ALocalizaProdutos.pas' {FlocalizaProduto},
  AProdutosKit in '..\mestoque\AProdutosKit.pas' {FProdutosKit},
  AProdutos in '..\mestoque\AProdutos.pas' {Fprodutos},
  ANovaClassificacao in '..\mestoque\ANovaClassificacao.pas' {FNovaClassificacao},
  AMontaKit in '..\mestoque\AMontaKit.pas' {FMontaKit},
  alocalizaclassificacao in '..\mestoque\alocalizaclassificacao.pas' {FLocalizaClassificacao},
  ACores in '..\mestoque\ACores.pas' {FCores},
  ATipoFundo in '..\mestoque\ATipoFundo.pas' {FTipoFundo},
  ATipoEmenda in '..\mestoque\ATipoEmenda.pas' {FTipoEmenda},
  AMaquinas in '..\mestoque\AMaquinas.pas' {FMaquinas},
  AEstagioProducao in '..\mestoque\AEstagioProducao.pas' {FEstagioProducao},
  ATipoEstagioProducao in '..\mestoque\ATipoEstagioProducao.pas' {FTipoEstagioProducao},
  ATipoCorte in '..\mestoque\ATipoCorte.pas' {FTipoCorte},
  UnCrystal in '..\magerais\UnCrystal.pas',
  ANovaCotacao in '..\mpontaloja\ANovaCotacao.pas' {FNovaCotacao},
  ANovoVendedor in '..\magerais\ANovoVendedor.pas' {FNovoVendedor},
  AVendedores in '..\magerais\AVendedores.pas' {FVendedores},
  AConsultaCondicaoPgto in '..\magerais\AConsultaCondicaoPgto.pas' {FConsultaCondicaoPgto},
  AFormasPagamento in '..\mfinanceiro\AFormasPagamento.pas' {FFormasPagamento},
  anovoservico in '..\mestoque\anovoservico.pas' {FNovoServico},
  unservicos in '..\mestoque\unservicos.pas',
  alocalizaservico in '..\mfaturamento\alocalizaservico.pas' {FlocalizaServico},
  UnVendedor in '..\magerais\UnVendedor.pas',
  ATipoCotacao in '..\mpontaloja\ATipoCotacao.pas' {FTipoCotacao},
  aoperacoesestoques in '..\mestoque\aoperacoesestoques.pas' {FOperacoesEstoques},
  AEmbalagem in '..\mpontaloja\AEmbalagem.pas' {FEmbalagem},
  AProdutoReferencia in '..\mpontaloja\AProdutoReferencia.pas' {FReferenciaProduto},
  AProdutosDevolvidos in '..\mpontaloja\AProdutosDevolvidos.pas' {FProdutosDevolvidos},
  AMostraObservacaoCliente in '..\mpontaloja\AMostraObservacaoCliente.pas' {FMostraObservacaoCliente},
  ANovaNotaFiscaisFor in '..\mestoque\ANovaNotaFiscaisFor.pas' {FNovaNotaFiscaisFor},
  UnNotasFiscaisFor in '..\mestoque\UnNotasFiscaisFor.pas',
  ANovaNatureza in '..\mfaturamento\ANovaNatureza.pas' {FNovaNatureza},
  ANaturezas in '..\mfaturamento\ANaturezas.pas' {FNaturezas},
  amovnatureza in '..\mfaturamento\amovnatureza.pas' {FMovNatureza},
  ANovoTecnico in '..\mpontaloja\ANovoTecnico.pas' {FNovoTecnico},
  ATecnicos in '..\mpontaloja\ATecnicos.pas' {FTecnicos},
  ANovaNotaFiscalNota in '..\mfaturamento\ANovaNotaFiscalNota.pas' {FNovaNotaFiscalNota},
  UnOrdemProducao in '..\mestoque\UnOrdemProducao.pas',
  aobservacoesnota in '..\mfaturamento\aobservacoesnota.pas' {FObservacoesNota},
  AImprimeEtiqueta in '..\mpontaloja\AImprimeEtiqueta.pas' {FImprimiEtiqueta},
  UnImpressaoEtiquetaCotacao in '..\mpontaloja\UnImpressaoEtiquetaCotacao.pas',
  AGeraOP in '..\mpontaloja\AGeraOP.pas' {FGerarOP},
  ANovaOrdemProducaoCadarco in '..\mestoque\ANovaOrdemProducaoCadarco.pas' {FNovaOrdemProducaoCadarco},
  AGeraEstagiosOP in '..\mpontaloja\AGeraEstagiosOP.pas' {FGeraEstagiosOP},
  ABaixaParcialCotacao in '..\mpontaloja\ABaixaParcialCotacao.pas' {FBaixaParcialCotacao},
  AConsultaBaixaParcial in '..\mpontaloja\AConsultaBaixaParcial.pas' {FConsultaBaixaParcial},
  ANovoECF in '..\mpontaloja\ANovoECF.pas' {FNovoECF},
  AFormaPagamentoECF in '..\mpontaloja\AFormaPagamentoECF.pas' {FFormaPagamentoECF},
  AOrdensProducaoCadarco in '..\mestoque\AOrdensProducaoCadarco.pas' {FOrdensProducaoCadarco},
  ANovaCobranca in '..\mfinanceiro\ANovaCobranca.pas' {FNovaCobranca},
  AHistoricoLigacao in '..\mfinanceiro\AHistoricoLigacao.pas' {FHistoricoLigacao},
  ACobrancas in '..\mfinanceiro\ACobrancas.pas' {FCobrancas},
  AMotivoInadimplencia in '..\mfinanceiro\AMotivoInadimplencia.pas' {FMotivoInadimplencia},
  aprofissoes in '..\magerais\aprofissoes.pas' {FProfissoes},
  asituacoesclientes in '..\magerais\asituacoesclientes.pas' {FSituacoesClientes},
  aregiaovenda in '..\magerais\aregiaovenda.pas' {FRegiaoVenda},
  ARamoAtividade in '..\mpontaloja\ARamoAtividade.pas' {FRamoAtividade},
  UnContrato in '..\mpontaloja\UnContrato.pas',
  ANovoContratoCliente in '..\mpontaloja\ANovoContratoCliente.pas' {FNovoContratoCliente},
  ATipoContrato in '..\mpontaloja\ATipoContrato.pas' {FTipoContrato},
  AContratosCliente in '..\mpontaloja\AContratosCliente.pas' {FContratosCliente},
  ANovoTeleMarketing in '..\mpontaloja\ANovoTeleMarketing.pas' {FNovoTeleMarketing},
  UnTeleMarketing in '..\mpontaloja\UnTeleMarketing.pas',
  ABrindesCliente in '..\mpontaloja\ABrindesCliente.pas' {FBrindesCliente},
  AAlteraVendedorCotacao in '..\mpontaloja\AAlteraVendedorCotacao.pas' {FAlteraVendedorCotacao},
  ATeleMarketings in '..\mpontaloja\ATeleMarketings.pas' {FTeleMarketings},
  AProdutosCliente in '..\mpontaloja\AProdutosCliente.pas' {FProdutosCliente},
  ANovoAgendamento in '..\mpontaloja\ANovoAgendamento.pas' {FNovoAgedamento},
  ATipoAgendamento in '..\mpontaloja\ATipoAgendamento.pas' {FTipoAgendamento},
  UnDaruma in '..\mpontaloja\UnDaruma.pas',
  ADonoProduto in '..\mpontaloja\ADonoProduto.pas' {FDonoProduto},
  AAcondicionamento in '..\mpontaloja\AAcondicionamento.pas' {FAcondicionamento},
  AGeraFracaoOP in '..\mpontaloja\AGeraFracaoOP.pas' {FGeraFracaoOP},
  AParentesCliente in '..\mpontaloja\AParentesCliente.pas' {FParentesClientes},
  UnChamado in '..\MChamado\UnChamado.pas',
  ANovoChamadoTecnico in '..\MChamado\ANovoChamadoTecnico.pas' {FNovoChamado},
  AOrdemProducaoGenerica in '..\mestoque\AOrdemProducaoGenerica.pas' {FOrdemProducaoGenerica},
  ANovaOrdemProducaoGenerica in '..\mestoque\ANovaOrdemProducaoGenerica.pas' {FNovaOrdemProducaoGenerica},
  AAlteraPermissaoFilial in 'AAlteraPermissaoFilial.pas' {FAlteraPermissaoFilial},
  AAlteraEstagioCotacao in '..\mpontaloja\AAlteraEstagioCotacao.pas' {FAlteraEstagioCotacao},
  AAlteraEstagioChamado in '..\mpontaloja\AAlteraEstagioChamado.pas' {FAlteraEstagioChamado},
  AHistoricoECobranca in '..\mfinanceiro\AHistoricoECobranca.pas' {FHistoricoECobranca},
  ALocalizaProdutoContrato in '..\MChamado\ALocalizaProdutoContrato.pas' {FLocalizaProdutoContrato},
  AChamadosTecnicos in '..\MChamado\AChamadosTecnicos.pas' {FChamadoTecnico},
  AHoraAgendaChamado in '..\MChamado\AHoraAgendaChamado.pas' {FHoraAgendaChamado},
  AAgendaChamados in '..\MChamado\AAgendaChamados.pas' {FAgendaChamados},
  AEfetuarPesquisaSatisfacao in '..\MChamado\AEfetuarPesquisaSatisfacao.pas' {FEfetuarPesquisaSatisfacao},
  UnPesquisaSatisfacao in '..\MChamado\UnPesquisaSatisfacao.pas',
  AMedico in '..\mpontaloja\AMedico.pas' {FMedico},
  AContatosCliente in '..\mpontaloja\AContatosCliente.pas' {FContatosCliente},
  AProdutosReserva in '..\mpontaloja\AProdutosReserva.pas' {FProdutosReserva},
  UnArgox in '..\magerais\UnArgox.pas',
  AChequesCP in '..\mfinanceiro\AChequesCP.pas' {FChequesCP},
  AConsultacheques in '..\mfinanceiro\AConsultacheques.pas' {FConsultaCheques},
  ANovaMaquina in '..\mestoque\ANovaMaquina.pas' {FNovaMaquina},
  APedidosPendentesFaturar in '..\mpontaloja\APedidosPendentesFaturar.pas' {FPedidosPendentesFaturar},
  UnProspect in '..\mcrm\UnProspect.pas',
  ATamanhos in '..\mpontaloja\ATamanhos.pas' {FTamanhos},
  UnUsuarios in 'UnUsuarios.pas',
  AContasAReceber in '..\mfinanceiro\AContasAReceber.pas' {FContasaReceber},
  ANovoContasaReceber in '..\mfinanceiro\ANovoContasaReceber.pas' {FNovoContasAReceber},
  agraficoscontasareceber in '..\mfinanceiro\agraficoscontasareceber.pas' {FGraficosCR},
  AManutencaoCR in '..\mfinanceiro\AManutencaoCR.pas' {FManutencaoCR},
  AMovComissoes in '..\mfinanceiro\AMovComissoes.pas' {FMovComissoes},
  AGraficosContasaPagar in '..\mfinanceiro\AGraficosContasaPagar.pas' {FGraficosCP},
  AConsolidarCR in '..\mfinanceiro\AConsolidarCR.pas' {FConsolidarCR},
  AContasAConsolidarCR in '..\mfinanceiro\AContasAConsolidarCR.pas' {FContasAConsolidarCR},
  AVisualizaLogReceber in '..\mfinanceiro\AVisualizaLogReceber.pas' {FVisualizaLogReceber},
  AComissaoClassificacaoVendedor in '..\mestoque\AComissaoClassificacaoVendedor.pas' {FComissaoClassificacaoVendedor},
  AProdutosOrcados in '..\MChamado\AProdutosOrcados.pas' {FProdutosOrcados},
  UnVersoes in '..\magerais\UnVersoes.pas',
  ANovoConcorrente in '..\mcrm\ANovoConcorrente.pas' {FNovoConcorrente},
  AConcorrentes in '..\mcrm\AConcorrentes.pas' {FConcorrentes},
  ANovaProposta in '..\mcrm\ANovaProposta.pas' {FNovaProposta},
  UnProposta in '..\mcrm\UnProposta.pas',
  ANovoProspect in '..\mcrm\ANovoProspect.pas' {FNovoProspect},
  AProspects in '..\mcrm\AProspects.pas' {FProspects},
  ANovaAgendaProspect in '..\mcrm\ANovaAgendaProspect.pas' {FNovaAgendaProspect},
  ANovoTelemarketingProspect in '..\mcrm\ANovoTelemarketingProspect.pas' {FNovoTelemarketingProspect},
  AProdutosProspect in '..\mcrm\AProdutosProspect.pas' {FProdutosProspect},
  AContatosProspect in '..\mcrm\AContatosProspect.pas' {FContatosProspect},
  AAlteraEstagioProposta in '..\mcrm\AAlteraEstagioProposta.pas' {FAlteraEstagioProposta},
  AMeioDivulgacao in '..\mcrm\AMeioDivulgacao.pas' {FMeioDivulgacao},
  AMotivoVenda in '..\mcrm\AMotivoVenda.pas' {FMotivoVenda},
  UnAmostra in '..\mcrm\UnAmostra.pas',
  ABaixaContasAReceberOO in '..\mfinanceiro\ABaixaContasAReceberOO.pas' {FBaixaContasaReceberOO},
  ANovoPedidoCompra in '..\mestoque\ANovoPedidoCompra.pas' {FNovoPedidoCompra},
  UnSolicitacaoCompra in '..\mestoque\UnSolicitacaoCompra.pas',
  UnPedidoCompra in '..\mestoque\UnPedidoCompra.pas',
  APedidosCompraAberto in '..\mestoque\APedidosCompraAberto.pas' {FPedidosCompraAberto},
  ACompradores in '..\mestoque\ACompradores.pas' {FCompradores},
  AChequesOO in '..\mfinanceiro\AChequesOO.pas' {FChequesOO},
  ABaixaContasaPagarOO in '..\mfinanceiro\ABaixaContasaPagarOO.pas' {FBaixaContasaPagarOO},
  ANovoEmailContasAReceber in '..\mfinanceiro\ANovoEmailContasAReceber.pas' {FNovoEmailContasAReceber},
  UnLembrete in '..\mpontaloja\UnLembrete.pas',
  ANovoLembrete in '..\mpontaloja\ANovoLembrete.pas' {FNovoLembrete},
  ASelecionarUsuarios in '..\mpontaloja\ASelecionarUsuarios.pas' {FSelecionarUsuarios},
  AVerificaLeituraLembrete in '..\MChamado\AVerificaLeituraLembrete.pas' {FVerificaLeituraLembrete},
  undespesas in '..\mfinanceiro\undespesas.pas',
  AContasAPagar in '..\mfinanceiro\AContasAPagar.pas' {FContasaPagar},
  adespesas in '..\mfinanceiro\adespesas.pas' {FDespesas},
  ageradespesasfixas in '..\mfinanceiro\ageradespesasfixas.pas' {FGeraDespesasFixas},
  ANovoContasaPagar in '..\mfinanceiro\ANovoContasaPagar.pas' {FNovoContasAPagar},
  ACentroCusto in '..\mfinanceiro\ACentroCusto.pas' {FCentroCusto},
  AManutencaoCP in '..\mfinanceiro\AManutencaoCP.pas' {FManutencaoCP},
  UnCaixa in '..\mcaixa\UnCaixa.pas',
  AGerarFracaoOPMaquinasCorte in '..\mpontaloja\AGerarFracaoOPMaquinasCorte.pas' {FGerarFracaoOPMaquinasCorte},
  ATipoChamado in '..\MChamado\ATipoChamado.pas' {FTipoChamado},
  ASetores in '..\mcrm\ASetores.pas' {FSetores},
  ABaixaConsumoProduto in '..\mestoque\ABaixaConsumoProduto.pas' {FBaixaConsumoProduto},
  AAlteraEstagioPedidoCompra in '..\mestoque\AAlteraEstagioPedidoCompra.pas' {FAlteraEstagioPedidoCompra},
  ANovoSetor in '..\mcrm\ANovoSetor.pas' {FNovoSetor},
  AMostraParPagarOO in '..\mfinanceiro\AMostraParPagarOO.pas' {FMostraParPagarOO},
  ASolicitacaoCompras in '..\mestoque\ASolicitacaoCompras.pas' {FSolicitacaoCompra},
  ANovaSolicitacaoCompra in '..\mestoque\ANovaSolicitacaoCompra.pas' {FNovoOrcamentoCompras},
  AAlteraEstagioOrcamento in '..\mestoque\AAlteraEstagioOrcamento.pas' {FAlteraEstagioOrcamentoCompra},
  ASolicitacaoCompraProdutosPendentes in '..\mestoque\ASolicitacaoCompraProdutosPendentes.pas' {FOrcamentoCompraProdutosPendentes},
  APedidoCompra in '..\mestoque\APedidoCompra.pas' {FPedidoCompra},
  ATipoProposta in '..\mcrm\ATipoProposta.pas' {FTipoProposta},
  UnZebra in '..\magerais\UnZebra.pas',
  ACompensaCheque in '..\mfinanceiro\ACompensaCheque.pas' {FCompensaCheque},
  APropostasCliente in '..\mcrm\APropostasCliente.pas' {FPropostasCliente},
  AMontaKitBastidor in '..\mestoque\AMontaKitBastidor.pas' {FMontaKitBastidor},
  ABaixaProdutosChamado in '..\MChamado\ABaixaProdutosChamado.pas' {FBaixaProdutosChamado},
  ARelOrdemSerra in '..\mestoque\ARelOrdemSerra.pas' {FRelOrdemSerra},
  AConsultaChamadoParcial in '..\MChamado\AConsultaChamadoParcial.pas' {FConsultaChamadoParcial},
  ACreditoCliente in '..\mfinanceiro\ACreditoCliente.pas' {FCreditoCliente},
  AAlteraEstagioFracaoOP in '..\mestoque\AAlteraEstagioFracaoOP.pas' {FAlteraEstagioFracaoOP},
  ANovoOrcamentoCompra in '..\mestoque\ANovoOrcamentoCompra.pas' {FNovoOrcamentoCompra},
  UnOrcamentoCompra in '..\mestoque\UnOrcamentoCompra.pas',
  AHorarioTrabalho in '..\mestoque\AHorarioTrabalho.pas' {FHorarioTrabalho},
  AFaixaEtaria in '..\mpontaloja\AFaixaEtaria.pas' {FFaixaEtaria},
  unEMarketing in '..\mpontaloja\unEMarketing.pas',
  AMarcas in '..\mpontaloja\AMarcas.pas' {FMarca},
  AAgendamentos in '..\mpontaloja\AAgendamentos.pas' {FAgendamentos},
  AAlteraEstagioAgendamento in '..\mpontaloja\AAlteraEstagioAgendamento.pas' {FAlteraEstagioAgendamento},
  AMetasVendedor in '..\mpontaloja\AMetasVendedor.pas' {FMetasVendedor},
  AConsultaLogSeparacaoConsumo in '..\mestoque\AConsultaLogSeparacaoConsumo.pas' {FConsultaLogSeparacaoConsumo},
  UnRave in '..\magerais\UnRave.pas',
  dmRave in '..\magerais\dmRave.pas' {dtRave: TDSServerModule},
  ANovaComposicao in '..\mestoque\ANovaComposicao.pas' {FNovaComposicao},
  AComposicoes in '..\mestoque\AComposicoes.pas' {FComposicoes},
  UnNFe in '..\mfaturamento\UnNFe.pas',
  ANovaCondicaoPagamento in '..\mpontaloja\ANovaCondicaoPagamento.pas' {FNovaCondicaoPagamento},
  ACondicaoPagamento in '..\mpontaloja\ACondicaoPagamento.pas' {FCondicaoPagamento},
  UnCondicaoPagamento in '..\mfinanceiro\UnCondicaoPagamento.pas',
  AProjetos in '..\mfinanceiro\AProjetos.pas' {FProjetos},
  AGeraFracaoOPProdutos in '..\mestoque\AGeraFracaoOPProdutos.pas' {FGeraFracaoOPProdutos},
  ACoeficientes in 'ACoeficientes.pas' {FCoeficientes},
  ANovoCoeficienteCusto in 'ANovoCoeficienteCusto.pas' {FNovoCoeficienteCusto},
  ACorpoEmailProposta in '..\mcrm\ACorpoEmailProposta.pas' {FCorpoEmailProposta},
  AMostraEstoqueChapas in '..\mestoque\AMostraEstoqueChapas.pas' {FMostraEstoqueChapas},
  UnDRave in '..\magerais\UnDRave.pas',
  UnProgramador1 in '..\magerais\UnProgramador1.pas',
  AAcessorio in '..\mestoque\AAcessorio.pas' {FAcessorio},
  AAplicacao in '..\mcrm\AAplicacao.pas' {FAplicacao},
  AAdicionaProdutosTerceirizacao in '..\mestoque\AAdicionaProdutosTerceirizacao.pas' {FAdicionaProdutosTerceirizacao},
  ALocalizaFracaoOP in '..\mestoque\ALocalizaFracaoOP.pas' {FLocalizaFracaoOP},
  ALimpaBancoDados in 'ALimpaBancoDados.pas' {FLimpaBancoDados},
  ANovoEstagio in '..\mestoque\ANovoEstagio.pas' {FNovoEstagio},
  AMapaCompras in '..\mestoque\AMapaCompras.pas' {FMapaCompras},
  AOrcamentoCompras in '..\mestoque\AOrcamentoCompras.pas' {FOrcamentoCompras},
  ASelecionarFornecedorMapaCompras in '..\mestoque\ASelecionarFornecedorMapaCompras.pas' {FSelecionaFornecedorMapaCompras},
  AOPProdutosAReservar in '..\mestoque\AOPProdutosAReservar.pas' {FOPProdutosAReservar},
  AMenuFiscalECF in '..\mefiPDV\AMenuFiscalECF.pas' {FMenuFiscalECF},
  AComandoFiscalFiltro in '..\mefiPDV\AComandoFiscalFiltro.pas' {FComandoFiscalFiltro},
  UnSpedFiscal in '..\mfaturamento\UnSpedFiscal.pas',
  ALiberaModulo in 'ALiberaModulo.pas' {FLiberaModulo},
  ATipoMateriaPrima in '..\mcrm\ATipoMateriaPrima.pas' {FTipoMateriaPrima},
  AFacas in '..\mestoque\AFacas.pas' {FFacas},
  AMostraObservacaoPedido in '..\mpontaloja\AMostraObservacaoPedido.pas' {FMostraObservacaoPedido},
  AProdutosClientePeca in '..\mpontaloja\AProdutosClientePeca.pas' {FProdutosClientePeca},
  ACampanhaVendas in '..\mpontaloja\ACampanhaVendas.pas' {FCampanhaVendas},
  ANovaCampanhaVendas in '..\mpontaloja\ANovaCampanhaVendas.pas' {FNovaCampanhaVendas},
  ATelefonesCliente in '..\mpontaloja\ATelefonesCliente.pas' {FTelefoneCliente},
  APermissaoRelatorio in 'APermissaoRelatorio.pas' {FPermissaoRelatorio},
  UnImpressaoRelatorio in '..\magerais\UnImpressaoRelatorio.pas',
  ARelPedido in '..\mpontaloja\ARelPedido.pas' {FRelPedido},
  AReciboLocacao in '..\mpontaloja\AReciboLocacao.pas' {FReciboLocacao},
  AConhecimentoTransporte in '..\mestoque\AConhecimentoTransporte.pas' {FConhecimentoTransporte},
  ANovoProdutoPro in '..\mestoque\ANovoProdutoPro.pas' {FNovoProdutoPro},
  AFaccionistas in '..\mestoque\AFaccionistas.pas' {FFaccionistas},
  AFracaoFaccionista in '..\mestoque\AFracaoFaccionista.pas' {FFracaoFaccionista},
  ANovaFaccionista in '..\mestoque\ANovaFaccionista.pas' {FNovaFaccionista},
  ANovaFracaoFaccionista in '..\mestoque\ANovaFracaoFaccionista.pas' {FNovaFracaoFaccionista},
  ATerceiroFaccionista in '..\mestoque\ATerceiroFaccionista.pas' {FTerceiroFaccionista},
  ARetornoFracaoFaccionista in '..\mestoque\ARetornoFracaoFaccionista.pas' {FRetornoFracaoFaccionista};

{$R *.RES}


begin
  RPDefine.DataID := IntToStr(Application.Handle);
  Application.Initialize;
  Application.HelpFile := '';
  Application.CreateForm(TFPrincipal, FPrincipal);
  if ParamCount = 0 then  // verifica se a parametros da base de dados
    Varia.ParametroBase := 'SisCorp'
  else
    varia.ParametroBase := CopiaAteChar(ParamStr(1),'/');

  if FPrincipal.AbreBaseDados(ParamStr(1)) then  // caso naum abra a base de dados
  begin
    FAbertura := TFAbertura.create(application);
    if (ParamStr(2) <> '') and (ParamStr(3) <> '') then    // caso a senha e ususario venham como parametro
    begin
      if FAbertura.VerificaSenha(Uppercase(ParamStr(2)),Uppercase(ParamStr(3)), ParamStr(4), ParamStr(5)) then // verifica a senha
         FAbertura.close
      else
         FAbertura.ShowModal;
      end
      else
         FAbertura.ShowModal;

    if Varia.StatusAbertura = 'CANCELADO' then
      FPrincipal.close
    else
      Application.Run;
  end
  else
    FPrincipal.close;
 end.
