program SisCorp;

uses
  Forms,
  Dialogs,
  rpDefine,
  FunString,
  APrincipal in 'APrincipal.pas' {FPrincipal},
  Abertura in '..\MaGerais\Abertura.pas' {FAbertura},
  Constantes in '..\MConfiguracoesSistema\Constantes.pas',
  UnAtualizacao in '..\MaGerais\UnAtualizacao.pas',
  AMenssagemAtualizando in 'AMenssagemAtualizando.pas' {FMensagemAtualizando},
  UnSistema in '..\magerais\UnSistema.pas',
  UnDados in '..\magerais\UnDados.pas',
  UnDadosCR in '..\mfinanceiro\UnDadosCR.pas',
  UnVersoes in '..\magerais\UnVersoes.pas',
  UnProgramador1 in '..\magerais\UnProgramador1.pas',
  UnProdutos in '..\mestoque\UnProdutos.pas',
  UnDadosProduto in '..\mestoque\UnDadosProduto.pas',
  UnClassificacao in '..\mestoque\UnClassificacao.pas',
  UnCodigoBarra in '..\mconfiguracoessistema\UnCodigoBarra.pas',
  UnSumarizaEstoque in '..\mestoque\UnSumarizaEstoque.pas',
  UnMoedas in '..\mconfiguracoessistema\UnMoedas.pas',
  UnAmostra in '..\mcrm\UnAmostra.pas',
  UnClientes in '..\magerais\UnClientes.pas',
  UnTeleMarketing in '..\mpontaloja\UnTeleMarketing.pas',
  UnProspect in '..\mcrm\UnProspect.pas',
  UnContasAReceber in '..\mfinanceiro\UnContasAReceber.pas',
  UnCaixa in '..\mcaixa\UnCaixa.pas',
  UnContasAPagar in '..\mfinanceiro\UnContasAPagar.pas',
  ABaixaContasaPagarOO in '..\mfinanceiro\ABaixaContasaPagarOO.pas' {FBaixaContasaPagarOO},
  AFormasPagamento in '..\mfinanceiro\AFormasPagamento.pas' {FFormasPagamento},
  AChequesCP in '..\mfinanceiro\AChequesCP.pas' {FChequesCP},
  AConsultacheques in '..\mfinanceiro\AConsultacheques.pas' {FConsultaCheques},
  UnClassesImprimir in '..\magerais\UnClassesImprimir.pas',
  UnComissoes in '..\mfinanceiro\UnComissoes.pas',
  AChequesOO in '..\mfinanceiro\AChequesOO.pas' {FChequesOO},
  AMostraParReceberOO in '..\mfinanceiro\AMostraParReceberOO.pas' {FMostraParReceberOO},
  abancos in '..\mfinanceiro\abancos.pas' {FBancos},
  AContas in '..\mfinanceiro\AContas.pas' {FContas},
  ANovaConta in '..\mfinanceiro\ANovaConta.pas' {FNovaConta},
  ANovoCliente in '..\magerais\ANovoCliente.pas' {FNovoCliente},
  UnZebra in '..\magerais\UnZebra.pas',
  UnOrdemProducao in '..\mestoque\UnOrdemProducao.pas',
  UnArgox in '..\magerais\UnArgox.pas',
  unEMarketing in '..\mpontaloja\unEMarketing.pas',
  ACondicaoPagamento in '..\mpontaloja\ACondicaoPagamento.pas' {FCondicaoPagamento},
  ANovaCondicaoPagamento in '..\mpontaloja\ANovaCondicaoPagamento.pas' {FNovaCondicaoPagamento},
  UnCondicaoPagamento in '..\mfinanceiro\UnCondicaoPagamento.pas',
  APlanoConta in '..\mfinanceiro\APlanoConta.pas' {FPlanoConta},
  ANovoPlanoConta in '..\mfinanceiro\ANovoPlanoConta.pas' {FNovoPlanoConta},
  AMarcas in '..\mpontaloja\AMarcas.pas' {FMarca},
  AFaixaEtaria in '..\mpontaloja\AFaixaEtaria.pas' {FFaixaEtaria},
  AHorarioTrabalho in '..\mestoque\AHorarioTrabalho.pas' {FHorarioTrabalho},
  ALocalizaProdutos in '..\mfaturamento\ALocalizaProdutos.pas' {FlocalizaProduto},
  ALocalizaClassificacao in '..\mestoque\ALocalizaClassificacao.pas' {FLocalizaClassificacao},
  AAcessorio in '..\mestoque\AAcessorio.pas' {FAcessorio},
  ANovaComposicao in '..\mestoque\ANovaComposicao.pas' {FNovaComposicao},
  AComposicoes in '..\mestoque\AComposicoes.pas' {FComposicoes},
  AMontaKit in '..\mestoque\AMontaKit.pas' {FMontaKit},
  AMontaKitBastidor in '..\mestoque\AMontaKitBastidor.pas' {FMontaKitBastidor},
  ACores in '..\mestoque\ACores.pas' {FCores},
  AEstagioProducao in '..\mestoque\AEstagioProducao.pas' {FEstagioProducao},
  ATipoEstagioProducao in '..\mestoque\ATipoEstagioProducao.pas' {FTipoEstagioProducao},
  AAcondicionamento in '..\mpontaloja\AAcondicionamento.pas' {FAcondicionamento},
  AEmbalagem in '..\mpontaloja\AEmbalagem.pas' {FEmbalagem},
  ATipoCorte in '..\mestoque\ATipoCorte.pas' {FTipoCorte},
  ATipoFundo in '..\mestoque\ATipoFundo.pas' {FTipoFundo},
  ATipoEmenda in '..\mestoque\ATipoEmenda.pas' {FTipoEmenda},
  AMaquinas in '..\mestoque\AMaquinas.pas' {FMaquinas},
  ANovaMaquina in '..\mestoque\ANovaMaquina.pas' {FNovaMaquina},
  AProdutosKit in '..\mestoque\AProdutosKit.pas' {FProdutosKit},
  AMeioDivulgacao in '..\mcrm\AMeioDivulgacao.pas' {FMeioDivulgacao},
  ANovoConcorrente in '..\mcrm\ANovoConcorrente.pas' {FNovoConcorrente},
  AConcorrentes in '..\mcrm\AConcorrentes.pas' {FConcorrentes},
  ACadCidades in '..\magerais\ACadCidades.pas' {FCidades},
  ACadEstados in '..\magerais\ACadEstados.pas' {FCadEstados},
  ACadPaises in '..\magerais\ACadPaises.pas' {FCadPaises},
  AConsultaRuas in '..\magerais\AConsultaRuas.pas' {FConsultaRuas},
  ANovoTecnico in '..\mpontaloja\ANovoTecnico.pas' {FNovoTecnico},
  ATecnicos in '..\mpontaloja\ATecnicos.pas' {FTecnicos},
  ARamoAtividade in '..\mpontaloja\ARamoAtividade.pas' {FRamoAtividade},
  ANovoVendedor in '..\magerais\ANovoVendedor.pas' {FNovoVendedor},
  AVendedores in '..\magerais\AVendedores.pas' {FVendedores},
  AMetasVendedor in '..\mpontaloja\AMetasVendedor.pas' {FMetasVendedor},
  ARegiaoVenda in '..\magerais\ARegiaoVenda.pas' {FRegiaoVenda},
  asituacoesclientes in '..\magerais\asituacoesclientes.pas' {FSituacoesClientes},
  AProfissoes in '..\magerais\AProfissoes.pas' {FProfissoes},
  AClientes in '..\magerais\AClientes.pas' {FClientes},
  UnContrato in '..\mpontaloja\UnContrato.pas',
  UnVendedor in '..\magerais\UnVendedor.pas',
  UnImpressaoBoleto in '..\magerais\UnImpressaoBoleto.pas',
  UnNotaFiscal in '..\mfaturamento\UnNotaFiscal.pas',
  UnNFe in '..\mfaturamento\UnNFe.pas',
  UnCotacao in '..\mpontaloja\UnCotacao.pas',
  dmRave in '..\magerais\dmRave.pas' {dtRave: TDSServerModule},
  UnRave in '..\magerais\UnRave.pas',
  UnDRave in '..\magerais\UnDRave.pas',
  ANovaNotaFiscalNota in '..\mfaturamento\ANovaNotaFiscalNota.pas' {FNovaNotaFiscalNota},
  UnImpressao in '..\magerais\UnImpressao.pas',
  ALocalizaServico in '..\mfaturamento\ALocalizaServico.pas' {FlocalizaServico},
  ANovoServico in '..\mestoque\ANovoServico.pas' {FNovoServico},
  UnServicos in '..\mestoque\UnServicos.pas',
  AMostraObservacaoCliente in '..\mpontaloja\AMostraObservacaoCliente.pas' {FMostraObservacaoCliente},
  AItensNatureza in '..\mfaturamento\AItensNatureza.pas' {FItensNatureza},
  AObservacoesNota in '..\mfaturamento\AObservacoesNota.pas' {FObservacoesNota},
  AConsultaCondicaoPgto in '..\magerais\AConsultaCondicaoPgto.pas' {FConsultaCondicaoPgto},
  ANaturezas in '..\mfaturamento\ANaturezas.pas' {FNaturezas},
  ANovaNatureza in '..\mfaturamento\ANovaNatureza.pas' {FNovaNatureza},
  AMovNatureza in '..\mfaturamento\AMovNatureza.pas' {FMovNatureza},
  aoperacoesestoques in '..\mestoque\aoperacoesestoques.pas' {FOperacoesEstoques},
  APropostasCliente in '..\mcrm\APropostasCliente.pas' {FPropostasCliente},
  UnCrystal in '..\magerais\UnCrystal.pas',
  UnProposta in '..\mcrm\UnProposta.pas',
  ACorpoEmailProposta in '..\mcrm\ACorpoEmailProposta.pas' {FCorpoEmailProposta},
  AChamadosTecnicos in '..\MChamado\AChamadosTecnicos.pas' {FChamadoTecnico},
  UnChamado in '..\MChamado\UnChamado.pas',
  AConsultaChamadoParcial in '..\MChamado\AConsultaChamadoParcial.pas' {FConsultaChamadoParcial},
  ABaixaProdutosChamado in '..\MChamado\ABaixaProdutosChamado.pas' {FBaixaProdutosChamado},
  ANovaProposta in '..\mcrm\ANovaProposta.pas' {FNovaProposta},
  AAplicacao in '..\mcrm\AAplicacao.pas' {FAplicacao},
  ATipoProposta in '..\mcrm\ATipoProposta.pas' {FTipoProposta},
  ASetores in '..\mcrm\ASetores.pas' {FSetores},
  ANovoSetor in '..\mcrm\ANovoSetor.pas' {FNovoSetor},
  AMotivoVenda in '..\mcrm\AMotivoVenda.pas' {FMotivoVenda},
  ANovoProspect in '..\mcrm\ANovoProspect.pas' {FNovoProspect},
  AProspects in '..\mcrm\AProspects.pas' {FProspects},
  ANovoTelemarketingProspect in '..\mcrm\ANovoTelemarketingProspect.pas' {FNovoTelemarketingProspect},
  AHistoricoLigacao in '..\mfinanceiro\AHistoricoLigacao.pas' {FHistoricoLigacao},
  AAlteraEstagioProposta in '..\mcrm\AAlteraEstagioProposta.pas' {FAlteraEstagioProposta},
  AContatosProspect in '..\mcrm\AContatosProspect.pas' {FContatosProspect},
  AProdutosProspect in '..\mcrm\AProdutosProspect.pas' {FProdutosProspect},
  ADonoProduto in '..\mpontaloja\ADonoProduto.pas' {FDonoProduto},
  ANovaAgendaProspect in '..\mcrm\ANovaAgendaProspect.pas' {FNovaAgendaProspect},
  AEfetuarPesquisaSatisfacao in '..\MChamado\AEfetuarPesquisaSatisfacao.pas' {FEfetuarPesquisaSatisfacao},
  UnPesquisaSatisfacao in '..\MChamado\UnPesquisaSatisfacao.pas',
  ANovoChamadoTecnico in '..\MChamado\ANovoChamadoTecnico.pas' {FNovoChamado},
  ATipoChamado in '..\MChamado\ATipoChamado.pas' {FTipoChamado},
  AProdutosOrcados in '..\MChamado\AProdutosOrcados.pas' {FProdutosOrcados},
  AAgendaChamados in '..\MChamado\AAgendaChamados.pas' {FAgendaChamados},
  AVerificaLeituraLembrete in '..\MChamado\AVerificaLeituraLembrete.pas' {FVerificaLeituraLembrete},
  UnLembrete in '..\mpontaloja\UnLembrete.pas',
  ANovoLembrete in '..\mpontaloja\ANovoLembrete.pas' {FNovoLembrete},
  ASelecionarUsuarios in '..\mpontaloja\ASelecionarUsuarios.pas' {FSelecionarUsuarios},
  AHoraAgendaChamado in '..\MChamado\AHoraAgendaChamado.pas' {FHoraAgendaChamado},
  ALocalizaProdutoContrato in '..\MChamado\ALocalizaProdutoContrato.pas' {FLocalizaProdutoContrato},
  AAlteraEstagioChamado in '..\mpontaloja\AAlteraEstagioChamado.pas' {FAlteraEstagioChamado},
  ANovaCotacao in '..\mpontaloja\ANovaCotacao.pas' {FNovaCotacao},
  ACreditoCliente in '..\mfinanceiro\ACreditoCliente.pas' {FCreditoCliente},
  ATamanhos in '..\mpontaloja\ATamanhos.pas' {FTamanhos},
  AMedico in '..\mpontaloja\AMedico.pas' {FMedico},
  ABrindesCliente in '..\mpontaloja\ABrindesCliente.pas' {FBrindesCliente},
  ANovoECF in '..\mpontaloja\ANovoECF.pas' {FNovoECF},
  UnECF in '..\mpontaloja\UnECF.pas',
  UnDaruma in '..\mpontaloja\UnDaruma.pas',
  AFormaPagamentoECF in '..\mpontaloja\AFormaPagamentoECF.pas' {FFormaPagamentoECF},
  ANovaNotaFiscaisFor in '..\mestoque\ANovaNotaFiscaisFor.pas' {FNovaNotaFiscaisFor},
  UnPedidoCompra in '..\mestoque\UnPedidoCompra.pas',
  UnSolicitacaoCompra in '..\mestoque\UnSolicitacaoCompra.pas',
  APedidosCompraAberto in '..\mestoque\APedidosCompraAberto.pas' {FPedidosCompraAberto},
  UnNotasFiscaisFor in '..\mestoque\UnNotasFiscaisFor.pas',
  AMostraEstoqueChapas in '..\mestoque\AMostraEstoqueChapas.pas' {FMostraEstoqueChapas},
  ANovoPedidoCompra in '..\mestoque\ANovoPedidoCompra.pas' {FNovoPedidoCompra},
  ALocalizaFracaoOP in '..\mestoque\ALocalizaFracaoOP.pas' {FLocalizaFracaoOP},
  AAdicionaProdutosTerceirizacao in '..\mestoque\AAdicionaProdutosTerceirizacao.pas' {FAdicionaProdutosTerceirizacao},
  ACompradores in '..\mestoque\ACompradores.pas' {FCompradores},
  AOrdemProducaoGenerica in '..\mestoque\AOrdemProducaoGenerica.pas' {FOrdemProducaoGenerica},
  AConsultaLogSeparacaoConsumo in '..\mestoque\AConsultaLogSeparacaoConsumo.pas' {FConsultaLogSeparacaoConsumo},
  AAlteraEstagioFracaoOP in '..\mestoque\AAlteraEstagioFracaoOP.pas' {FAlteraEstagioFracaoOP},
  AGerarFracaoOPMaquinasCorte in '..\mpontaloja\AGerarFracaoOPMaquinasCorte.pas' {FGerarFracaoOPMaquinasCorte},
  ARelOrdemSerra in '..\mestoque\ARelOrdemSerra.pas' {FRelOrdemSerra},
  APedidoCompra in '..\mestoque\APedidoCompra.pas' {FPedidoCompra},
  ASolicitacaoCompras in '..\mestoque\ASolicitacaoCompras.pas' {FSolicitacaoCompra},
  ASolicitacaoCompraProdutosPendentes in '..\mestoque\ASolicitacaoCompraProdutosPendentes.pas' {FSolicitacaoCompraProdutosPendentes},
  ANovoOrcamentoCompra in '..\mestoque\ANovoOrcamentoCompra.pas' {FNovoOrcamentoCompra},
  UnOrcamentoCompra in '..\mestoque\UnOrcamentoCompra.pas',
  ANovaSolicitacaoCompra in '..\mestoque\ANovaSolicitacaoCompra.pas' {FNovaSolicitacaoCompras},
  AAlteraEstagioOrcamento in '..\mestoque\AAlteraEstagioOrcamento.pas' {FAlteraEstagioOrcamentoCompra},
  AAgendamentos in '..\mpontaloja\AAgendamentos.pas' {FAgendamentos},
  AAlteraEstagioAgendamento in '..\mpontaloja\AAlteraEstagioAgendamento.pas' {FAlteraEstagioAgendamento},
  ANovoTeleMarketing in '..\mpontaloja\ANovoTeleMarketing.pas' {FNovoTeleMarketing},
  AAlteraEstagioPedidoCompra in '..\mestoque\AAlteraEstagioPedidoCompra.pas' {FAlteraEstagioPedidoCompra},
  AContatosCliente in '..\mpontaloja\AContatosCliente.pas' {FContatosCliente},
  ANovoAgendamento in '..\mpontaloja\ANovoAgendamento.pas' {FNovoAgedamento},
  ATipoAgendamento in '..\mpontaloja\ATipoAgendamento.pas' {FTipoAgendamento},
  ANovoContratoCliente in '..\mpontaloja\ANovoContratoCliente.pas' {FNovoContratoCliente},
  ATipoContrato in '..\mpontaloja\ATipoContrato.pas' {FTipoContrato},
  AProdutosCliente in '..\mpontaloja\AProdutosCliente.pas' {FProdutosCliente},
  ATeleMarketings in '..\mpontaloja\ATeleMarketings.pas' {FTeleMarketings},
  ABaixaConsumoProduto in '..\mestoque\ABaixaConsumoProduto.pas' {FBaixaConsumoProduto},
  ANovaOrdemProducaoGenerica in '..\mestoque\ANovaOrdemProducaoGenerica.pas' {FNovaOrdemProducaoGenerica},
  AGeraFracaoOPProdutos in '..\mestoque\AGeraFracaoOPProdutos.pas' {FGeraFracaoOPProdutos},
  AGeraFracaoOP in '..\mpontaloja\AGeraFracaoOP.pas' {FGeraFracaoOP},
  AGeraEstagiosOP in '..\mpontaloja\AGeraEstagiosOP.pas' {FGeraEstagiosOP},
  AProdutosDevolvidos in '..\mpontaloja\AProdutosDevolvidos.pas' {FProdutosDevolvidos},
  AProdutoReferencia in '..\mpontaloja\AProdutoReferencia.pas' {FReferenciaProduto},
  ATipoCotacao in '..\mpontaloja\ATipoCotacao.pas' {FTipoCotacao},
  AProdutosReserva in '..\mpontaloja\AProdutosReserva.pas' {FProdutosReserva},
  AParentesCliente in '..\mpontaloja\AParentesCliente.pas' {FParentesClientes},
  AContratosCliente in '..\mpontaloja\AContratosCliente.pas' {FContratosCliente},
  ANovaCobranca in '..\mfinanceiro\ANovaCobranca.pas' {FNovaCobranca},
  ANovoEmailContasAReceber in '..\mfinanceiro\ANovoEmailContasAReceber.pas' {FNovoEmailContasAReceber},
  ABaixaContasAReceberOO in '..\mfinanceiro\ABaixaContasAReceberOO.pas' {FBaixaContasaReceberOO},
  AContasAReceber in '..\mfinanceiro\AContasAReceber.pas' {FContasaReceber},
  ACompensaCheque in '..\mfinanceiro\ACompensaCheque.pas' {FCompensaCheque},
  AContasAPagar in '..\mfinanceiro\AContasAPagar.pas' {FContasaPagar},
  undespesas in '..\mfinanceiro\undespesas.pas',
  AManutencaoCP in '..\mfinanceiro\AManutencaoCP.pas' {FManutencaoCP},
  AMostraParPagarOO in '..\mfinanceiro\AMostraParPagarOO.pas' {FMostraParPagarOO},
  AMovComissoes in '..\mfinanceiro\AMovComissoes.pas' {FMovComissoes},
  AGraficosContasaPagar in '..\mfinanceiro\AGraficosContasaPagar.pas' {FGraficosCP},
  ageradespesasfixas in '..\mfinanceiro\ageradespesasfixas.pas' {FGeraDespesasFixas},
  ANovoContasaPagar in '..\mfinanceiro\ANovoContasaPagar.pas' {FNovoContasAPagar},
  AProjetos in '..\mfinanceiro\AProjetos.pas' {FProjetos},
  ACentroCusto in '..\mfinanceiro\ACentroCusto.pas' {FCentroCusto},
  adespesas in '..\mfinanceiro\adespesas.pas' {FDespesas},
  ANovoEstagio in '..\mestoque\ANovoEstagio.pas' {FNovoEstagio},
  ACobrancas in '..\mfinanceiro\ACobrancas.pas' {FCobrancas},
  AVisualizaLogReceber in '..\mfinanceiro\AVisualizaLogReceber.pas' {FVisualizaLogReceber},
  AConsolidarCR in '..\mfinanceiro\AConsolidarCR.pas' {FConsolidarCR},
  AContasAConsolidarCR in '..\mfinanceiro\AContasAConsolidarCR.pas' {FContasAConsolidarCR},
  AManutencaoCR in '..\mfinanceiro\AManutencaoCR.pas' {FManutencaoCR},
  agraficoscontasareceber in '..\mfinanceiro\agraficoscontasareceber.pas' {FGraficosCR},
  ANovoContasaReceber in '..\mfinanceiro\ANovoContasaReceber.pas' {FNovoContasAReceber},
  AHistoricoECobranca in '..\mfinanceiro\AHistoricoECobranca.pas' {FHistoricoECobranca},
  AMotivoInadimplencia in '..\mfinanceiro\AMotivoInadimplencia.pas' {FMotivoInadimplencia},
  ACotacao in '..\mpontaloja\ACotacao.pas' {FCotacao},
  APedidosPendentesFaturar in '..\mpontaloja\APedidosPendentesFaturar.pas' {FPedidosPendentesFaturar},
  AAlteraEstagioCotacao in '..\mpontaloja\AAlteraEstagioCotacao.pas' {FAlteraEstagioCotacao},
  AAlteraVendedorCotacao in '..\mpontaloja\AAlteraVendedorCotacao.pas' {FAlteraVendedorCotacao},
  AOrdensProducaoCadarco in '..\mestoque\AOrdensProducaoCadarco.pas' {FOrdensProducaoCadarco},
  ANovaOrdemProducaoCadarco in '..\mestoque\ANovaOrdemProducaoCadarco.pas' {FNovaOrdemProducaoCadarco},
  AConsultaBaixaParcial in '..\mpontaloja\AConsultaBaixaParcial.pas' {FConsultaBaixaParcial},
  ABaixaParcialCotacao in '..\mpontaloja\ABaixaParcialCotacao.pas' {FBaixaParcialCotacao},
  AGeraOP in '..\mpontaloja\AGeraOP.pas' {FGerarOP},
  AImprimeEtiqueta in '..\mpontaloja\AImprimeEtiqueta.pas' {FImprimiEtiqueta},
  UnImpressaoEtiquetaCotacao in '..\mpontaloja\UnImpressaoEtiquetaCotacao.pas',
  AOPProdutosAReservar in '..\mestoque\AOPProdutosAReservar.pas' {FOPProdutosAReservar},
  AMapaCompras in '..\mestoque\AMapaCompras.pas' {FMapaCompras},
  AOrcamentoCompras in '..\mestoque\AOrcamentoCompras.pas' {FOrcamentoCompras},
  ASelecionarFornecedorMapaCompras in '..\mestoque\ASelecionarFornecedorMapaCompras.pas' {FSelecionaFornecedorMapaCompras},
  AComandoFiscalFiltro in '..\mefiPDV\AComandoFiscalFiltro.pas' {FComandoFiscalFiltro},
  AMenuFiscalECF in '..\mefiPDV\AMenuFiscalECF.pas' {FMenuFiscalECF},
  UnPrincipal in '..\magerais\UnPrincipal.pas',
  UnSpedFiscal in '..\mfaturamento\UnSpedFiscal.pas',
  ATipoMateriaPrima in '..\mcrm\ATipoMateriaPrima.pas' {FTipoMateriaPrima},
  AFacas in '..\mestoque\AFacas.pas' {FFacas},
  AMostraObservacaoPedido in '..\mpontaloja\AMostraObservacaoPedido.pas' {FMostraObservacaoPedido},
  AProdutosClientePeca in '..\mpontaloja\AProdutosClientePeca.pas' {FProdutosClientePeca},
  ATelefonesCliente in '..\mpontaloja\ATelefonesCliente.pas' {FTelefoneCliente},
  AReciboLocacao in '..\mpontaloja\AReciboLocacao.pas' {FReciboLocacao},
  ANovoProdutoPro in '..\mestoque\ANovoProdutoPro.pas' {FNovoProdutoPro},
  AConhecimentoTransporte in '..\mestoque\AConhecimentoTransporte.pas' {FConhecimentoTransporte},
  AFaccionistas in '..\mestoque\AFaccionistas.pas' {FFaccionistas},
  AFracaoFaccionista in '..\mestoque\AFracaoFaccionista.pas' {FFracaoFaccionista},
  ANovaFaccionista in '..\mestoque\ANovaFaccionista.pas' {FNovaFaccionista},
  ANovaFracaoFaccionista in '..\mestoque\ANovaFracaoFaccionista.pas' {FNovaFracaoFaccionista},
  ARetornoFracaoFaccionista in '..\mestoque\ARetornoFracaoFaccionista.pas' {FRetornoFracaoFaccionista},
  ATerceiroFaccionista in '..\mestoque\ATerceiroFaccionista.pas' {FTerceiroFaccionista};

{$R *.RES}
var
  ParametroNomeSistema : String;

begin
  Application.Initialize;
  Application.Title := 'SisCorp';
  Application.CreateForm(TFPrincipal, FPrincipal);
  varia.ParametroBase := CopiaAteChar(ParamStr(1),'/');
  VglParametroOficial := ParamStr(2);

  if ParamCount < 2 then
  begin
    VglParametroOficial := '1';
    if ParamCount < 1 Then
      Varia.parametroBase := 'SisCorp';
  end;

  if VglParametroOficial = '0' Then
    FPrincipal.MostraMenssagemDemostracao;

  ParametroNomeSistema := 'SisCorp - ' + ParamStr(1);
  Fprincipal.VplParametroBaseDados :=  ParamStr(1);
  if Fprincipal.VplParametroBaseDados = '' then
    Fprincipal.VplParametroBaseDados := 'SisCorp';

  if not FPrincipal.ProgramaEmExecucao(ParametroNomeSistema) then
  begin
    if FPrincipal.AbreBaseDados(ParamStr(1)) then
    begin
      FPrincipal.Caption := ParametroNomeSistema;
      FPrincipal.ResetaIni;
      FAbertura := TFAbertura.create(application);
      FAbertura.ShowModal;
      if Varia.StatusAbertura = 'CANCELADO' then
        FPrincipal.close
      else
      begin
        FPrincipal.CarregaNomeUsuario;
        Application.Run;
      end;
    end;
  end
  else
    FPrincipal.close;
end.
